{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.chocoboy.cascade",
    "module": "cascade-neoforge",
    "version": "1.0.0+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cascade-neoforge-1.0.0+26.1.jar",
          "url": "cascade-neoforge-1.0.0+26.1.jar",
          "size": 303644,
          "sha512": "f5105ee74c4b46c5ab62590286d843c2142420c64cb716832e8c858aa9dec06f3ff609088985e9aa493f15e69709f4c23e281ac7823423b00545761a9bc94a5e",
          "sha256": "5bc93ba9d824727673d9f6d3aecffe4c58e100d7560c1a7144f302f790cfd0a2",
          "sha1": "838dff77f144bba94afbe508dfda2d3b3710dd57",
          "md5": "8216494ef4a314b806cac7ce87c8d9ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cascade-neoforge-1.0.0+26.1.jar",
          "url": "cascade-neoforge-1.0.0+26.1.jar",
          "size": 303644,
          "sha512": "f5105ee74c4b46c5ab62590286d843c2142420c64cb716832e8c858aa9dec06f3ff609088985e9aa493f15e69709f4c23e281ac7823423b00545761a9bc94a5e",
          "sha256": "5bc93ba9d824727673d9f6d3aecffe4c58e100d7560c1a7144f302f790cfd0a2",
          "sha1": "838dff77f144bba94afbe508dfda2d3b3710dd57",
          "md5": "8216494ef4a314b806cac7ce87c8d9ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cascade-neoforge-1.0.0+26.1-sources.jar",
          "url": "cascade-neoforge-1.0.0+26.1-sources.jar",
          "size": 186726,
          "sha512": "c19f864401733b589476a119b081ab757fc78a68bfd619d72122314d0b7c3aaf5aa6158696746a69e0254a603b4bdfb8073aa835fbd5e946dfc341c999099e6d",
          "sha256": "3b0a664942adaaafdcd6589a2ee719c16f0b4f5edb5b1fb0fa05fb6086600228",
          "sha1": "00990afed8002303f2378804bbaa747ac9e4b629",
          "md5": "2153367d56cc4e6bc1c22ba43bd4f1cf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cascade-neoforge-1.0.0+26.1-javadoc.jar",
          "url": "cascade-neoforge-1.0.0+26.1-javadoc.jar",
          "size": 4648131,
          "sha512": "a6f9dfbdb70e2800c9e6da778e7ca727171b89c3b03975ad1c827f2efec79f3dc998c11b2091c5dbeafb52991928526ea37efa98d5356412d2efd7e6353da87f",
          "sha256": "2176c0bc9f6f922c9f2b6bafa2e23d24afd3ec5a819b8bf7e22f7295ba67034f",
          "sha1": "ff91cf9fe5b9c308acc75698cd32ed39d466cb79",
          "md5": "e6f7aaae22857905fe7987f7077e59fb"
        }
      ]
    }
  ]
}
