{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.chocoboy.cascade",
    "module": "cascade-neoforge",
    "version": "1.0.0+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cascade-neoforge-1.0.0+26.1.jar",
          "url": "cascade-neoforge-1.0.0+26.1.jar",
          "size": 303631,
          "sha512": "6f2961c7d5aaf54b83b4a5048603b161cb8107d35ea502637d98ca38195f571159de0a0bc096be864c97db7855b072268e4250fa408247f472c6f76e864f938b",
          "sha256": "eede3b9d6648866b1aef590ba73e7d6a258661cde6323fac88cd18f7a86b3e49",
          "sha1": "891e0b9b60cff8e6252c6f1c84eca704a80380fb",
          "md5": "3c6dc673f8ae8aa7a8e5d129f997a363"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cascade-neoforge-1.0.0+26.1.jar",
          "url": "cascade-neoforge-1.0.0+26.1.jar",
          "size": 303631,
          "sha512": "6f2961c7d5aaf54b83b4a5048603b161cb8107d35ea502637d98ca38195f571159de0a0bc096be864c97db7855b072268e4250fa408247f472c6f76e864f938b",
          "sha256": "eede3b9d6648866b1aef590ba73e7d6a258661cde6323fac88cd18f7a86b3e49",
          "sha1": "891e0b9b60cff8e6252c6f1c84eca704a80380fb",
          "md5": "3c6dc673f8ae8aa7a8e5d129f997a363"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cascade-neoforge-1.0.0+26.1-sources.jar",
          "url": "cascade-neoforge-1.0.0+26.1-sources.jar",
          "size": 186713,
          "sha512": "d283ef2fce893077ecececfbd30322b1d61c2a6b3a6860afba35b66ee66c36e6398bd9871ca0bd7cc4599259070fe3ab17fe12a9113ba6a8b0f617ff707a65a4",
          "sha256": "306cf4daa17e790e08a5fd8629218cda098bdab3270b8f38f293be2cc0e0f4e1",
          "sha1": "1a60b32975c05eef854c3a40a22350cdf0e32480",
          "md5": "73e6d8d8a4bbf23519b22ff1042ca072"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cascade-neoforge-1.0.0+26.1-javadoc.jar",
          "url": "cascade-neoforge-1.0.0+26.1-javadoc.jar",
          "size": 4648131,
          "sha512": "a6f9dfbdb70e2800c9e6da778e7ca727171b89c3b03975ad1c827f2efec79f3dc998c11b2091c5dbeafb52991928526ea37efa98d5356412d2efd7e6353da87f",
          "sha256": "2176c0bc9f6f922c9f2b6bafa2e23d24afd3ec5a819b8bf7e22f7295ba67034f",
          "sha1": "ff91cf9fe5b9c308acc75698cd32ed39d466cb79",
          "md5": "e6f7aaae22857905fe7987f7077e59fb"
        }
      ]
    }
  ]
}
